import { Product } from '../types';

export const products: Product[] = [
  // --- CRM ---
  {
    id: 'crm-1',
    name: 'Salesforce Industries',
    website: 'salesforce.com',
    employees: '79,000+',
    revenue: '$34.8B',
    coreOffering: 'Enterprise Cloud CRM',
    marketShare: 28,
    category: 'CRM',
    description: 'The market leader offering deep customization for insurance carriers and large brokerages.',
    logoInitial: 'S'
  },
  {
    id: 'crm-2',
    name: 'AgencyBloc',
    website: 'agencybloc.com',
    employees: '150+',
    revenue: '$25M',
    coreOffering: 'AMS & CRM for Life/Health',
    marketShare: 10,
    category: 'CRM',
    description: '#1 recommended insurance industry growth platform for life and health agencies.',
    logoInitial: 'A'
  },
  {
    id: 'crm-3',
    name: 'Better Agency',
    website: 'betteragency.io',
    employees: '50+',
    revenue: '$8M',
    coreOffering: 'Automation-First CRM',
    marketShare: 4,
    category: 'CRM',
    description: 'A modern CRM focusing on automation and sales pipelines for independent agents.',
    logoInitial: 'B'
  },
  {
    id: 'crm-4',
    name: 'HubSpot CRM',
    website: 'hubspot.com',
    employees: '7,000+',
    revenue: '$1.7B',
    coreOffering: 'Inbound Marketing & Sales',
    marketShare: 15,
    category: 'CRM',
    description: 'Versatile platform widely used by insurtech startups for its ease of use and marketing integration.',
    logoInitial: 'H'
  },
  {
    id: 'crm-5',
    name: 'Microsoft Dynamics 365',
    website: 'dynamics.microsoft.com',
    employees: '220,000+',
    revenue: '$198B (MS)',
    coreOffering: 'Enterprise ERP & CRM',
    marketShare: 18,
    category: 'CRM',
    description: 'Major player offering flexible, scalable CRM solutions often used by large carriers.',
    logoInitial: 'M'
  },
  {
    id: 'crm-6',
    name: 'Applied Epic',
    website: 'appliedsystems.com',
    employees: '2,500+',
    revenue: '$500M+',
    coreOffering: 'Agency Management System',
    marketShare: 12,
    category: 'CRM',
    description: 'Comprehensive agency management system widely used in the P&C sector.',
    logoInitial: 'A'
  },
  {
    id: 'crm-7',
    name: 'Pipedrive',
    website: 'pipedrive.com',
    employees: '900+',
    revenue: '$100M+',
    coreOffering: 'Visual Sales CRM',
    marketShare: 5,
    category: 'CRM',
    description: 'Visual CRM designed to keep insurance agents organized and focused on closing deals.',
    logoInitial: 'P'
  },
  {
    id: 'crm-8',
    name: 'Shape',
    website: 'shape.software',
    employees: '50+',
    revenue: '$10M+',
    coreOffering: 'Insurance Broker CRM',
    marketShare: 3,
    category: 'CRM',
    description: 'Cloud-based CRM and marketing automation specifically for insurance professionals.',
    logoInitial: 'S'
  },
  {
    id: 'crm-9',
    name: 'Zoho CRM',
    website: 'zoho.com',
    employees: '12,000+',
    revenue: '$1B+',
    coreOffering: 'Customizable CRM Suite',
    marketShare: 5,
    category: 'CRM',
    description: 'Affordable, highly customizable option popular with smaller agencies.',
    logoInitial: 'Z'
  },

  // --- Lead Generation ---
  {
    id: 'lead-1',
    name: 'SmartFinancial',
    website: 'smartfinancial.com',
    employees: '200+',
    revenue: '$50M+',
    coreOffering: 'Real-time Leads & Calls',
    marketShare: 12,
    category: 'Lead Generation',
    description: 'Provides high-intent insurance leads and live transfers for agents across the US.',
    logoInitial: 'S'
  },
  {
    id: 'lead-2',
    name: 'EverQuote',
    website: 'everquote.com',
    employees: '500+',
    revenue: '$400M',
    coreOffering: 'Data-Driven Marketplace',
    marketShare: 18,
    category: 'Lead Generation',
    description: 'One of the largest online marketplaces for insurance shopping in the US.',
    logoInitial: 'E'
  },
  {
    id: 'lead-3',
    name: 'QuoteWizard',
    website: 'quotewizard.com',
    employees: '150+',
    revenue: '$150M',
    coreOffering: 'Consumer Leads',
    marketShare: 15,
    category: 'Lead Generation',
    description: 'Owned by LendingTree, offering extensive reach in auto, home, and health insurance leads.',
    logoInitial: 'Q'
  },
  {
    id: 'lead-4',
    name: 'Datalot',
    website: 'datalot.com',
    employees: '100+',
    revenue: '$40M',
    coreOffering: 'Pay-Per-Call Mobile',
    marketShare: 7,
    category: 'Lead Generation',
    description: 'Specializes in live calls and mobile traffic generation for carriers.',
    logoInitial: 'D'
  },
  {
    id: 'lead-5',
    name: 'EngageBay',
    website: 'engagebay.com',
    employees: '100+',
    revenue: '$10M+',
    coreOffering: 'All-in-One Growth Suite',
    marketShare: 5,
    category: 'Lead Generation',
    description: 'Affordable integrated marketing, sales, and service automation for small agencies.',
    logoInitial: 'E'
  },
  {
    id: 'lead-6',
    name: 'ZipQuote',
    website: 'zipquote.com',
    employees: '100+',
    revenue: '$20M+',
    coreOffering: 'Lead Exchange',
    marketShare: 6,
    category: 'Lead Generation',
    description: 'Delivers high-quality insurance leads and calls with a focus on conversion.',
    logoInitial: 'Z'
  },
  {
    id: 'lead-7',
    name: 'Hometown Quotes',
    website: 'hometownquotes.com',
    employees: '50+',
    revenue: '$15M+',
    coreOffering: 'Local Leads',
    marketShare: 5,
    category: 'Lead Generation',
    description: 'Focused on connecting local agents with high-intent shoppers in their area.',
    logoInitial: 'H'
  },
  {
    id: 'lead-8',
    name: 'AnyBiz',
    website: 'anybiz.io',
    employees: '50+',
    revenue: '$5M+',
    coreOffering: 'AI Sales Agents',
    marketShare: 3,
    category: 'Lead Generation',
    description: 'AI-powered platform that acts as a fully autonomous sales team for lead gen.',
    logoInitial: 'A'
  },
  {
    id: 'lead-9',
    name: 'SalesBlink',
    website: 'salesblink.io',
    employees: '20+',
    revenue: '$2M+',
    coreOffering: 'Cold Outreach Automation',
    marketShare: 2,
    category: 'Lead Generation',
    description: 'AI-powered cold email outreach tool helping sales teams close more deals.',
    logoInitial: 'S'
  },
  {
    id: 'lead-10',
    name: 'LeadSend',
    website: 'leadsend.com',
    employees: '20+',
    revenue: '$1M+',
    coreOffering: 'Insurance Lead Gen',
    marketShare: 2,
    category: 'Lead Generation',
    description: 'AI-powered insurance lead generation specialized for high intent prospects.',
    logoInitial: 'L'
  },

  // --- Marketing Automation ---
  {
    id: 'mar-1',
    name: 'ActiveCampaign',
    website: 'activecampaign.com',
    employees: '1,000+',
    revenue: '$165M',
    coreOffering: 'CX Automation',
    marketShare: 12,
    category: 'Marketing Automation',
    description: 'Popular among agencies for its powerful visual automation builder and CRM capabilities.',
    logoInitial: 'A'
  },
  {
    id: 'mar-2',
    name: 'Salesforce Marketing Cloud',
    website: 'salesforce.com/marketing',
    employees: '70,000+',
    revenue: '$30B+',
    coreOffering: 'Enterprise Marketing',
    marketShare: 18,
    category: 'Marketing Automation',
    description: 'Enterprise-grade marketing automation for complex customer journeys.',
    logoInitial: 'S'
  },
  {
    id: 'mar-3',
    name: 'HubSpot Marketing',
    website: 'hubspot.com',
    employees: '7,000+',
    revenue: '$1.7B',
    coreOffering: 'Inbound Marketing',
    marketShare: 20,
    category: 'Marketing Automation',
    description: 'Comprehensive marketing automation with free tier available.',
    logoInitial: 'H'
  },
  {
    id: 'mar-4',
    name: 'Marketo (Adobe)',
    website: 'marketo.com',
    employees: '1,500+',
    revenue: '$400M+',
    coreOffering: 'B2B Automation',
    marketShare: 10,
    category: 'Marketing Automation',
    description: 'Robust solution for large carriers needing complex lead scoring and account-based marketing.',
    logoInitial: 'M'
  },
  {
    id: 'mar-5',
    name: 'Agency Revolution',
    website: 'agencyrevolution.com',
    employees: '50+',
    revenue: '$10M',
    coreOffering: 'Insurance Marketing',
    marketShare: 6,
    category: 'Marketing Automation',
    description: 'Marketing automation software built specifically for independent insurance agents.',
    logoInitial: 'A'
  },
  {
    id: 'mar-6',
    name: 'Mailchimp',
    website: 'mailchimp.com',
    employees: '1,200+',
    revenue: '$800M',
    coreOffering: 'Email Marketing',
    marketShare: 15,
    category: 'Marketing Automation',
    description: 'User-friendly all-in-one marketing platform for small businesses.',
    logoInitial: 'M'
  },
  {
    id: 'mar-7',
    name: 'Levitate',
    website: 'levitate.ai',
    employees: '200+',
    revenue: '$30M',
    coreOffering: 'Keep-in-touch Marketing',
    marketShare: 5,
    category: 'Marketing Automation',
    description: 'Built for relationship-based businesses to maintain personal connections.',
    logoInitial: 'L'
  },
  {
    id: 'mar-8',
    name: 'PathwayPort',
    website: 'pathwayport.com',
    employees: '50+',
    revenue: '$5M',
    coreOffering: 'Automated Client Comms',
    marketShare: 3,
    category: 'Marketing Automation',
    description: 'Insurance-specific marketing automation to engage policyholders.',
    logoInitial: 'P'
  },

  // --- Lead Enrichment ---
  {
    id: 'enrich-1',
    name: 'ZoomInfo',
    website: 'zoominfo.com',
    employees: '3,000+',
    revenue: '$1.1B',
    coreOffering: 'B2B Database',
    marketShare: 25,
    category: 'Lead Enrichment',
    description: 'The gold standard for B2B contact data, used by commercial lines producers.',
    logoInitial: 'Z'
  },
  {
    id: 'enrich-2',
    name: 'Apollo.io',
    website: 'apollo.io',
    employees: '500+',
    revenue: '$100M+',
    coreOffering: 'Sales Intelligence',
    marketShare: 15,
    category: 'Lead Enrichment',
    description: 'Engagement platform with a massive database of contacts and enrichment tools.',
    logoInitial: 'A'
  },
  {
    id: 'enrich-3',
    name: 'LinkedIn Sales Navigator',
    website: 'linkedin.com/sales',
    employees: '20,000+',
    revenue: '$10B+',
    coreOffering: 'Social Selling',
    marketShare: 20,
    category: 'Lead Enrichment',
    description: 'Premier tool for finding and building relationships with prospects via professional networks.',
    logoInitial: 'L'
  },
  {
    id: 'enrich-4',
    name: 'Clearbit',
    website: 'clearbit.com',
    employees: '100+',
    revenue: '$30M',
    coreOffering: 'Real-time API',
    marketShare: 8,
    category: 'Lead Enrichment',
    description: 'Excellent for enriching inbound leads instantly to route commercial opportunities.',
    logoInitial: 'C'
  },
  {
    id: 'enrich-5',
    name: 'Lusha',
    website: 'lusha.com',
    employees: '250+',
    revenue: '$50M+',
    coreOffering: 'Contact Info Extension',
    marketShare: 7,
    category: 'Lead Enrichment',
    description: 'Crowdsourced data platform for finding B2B contact information easily.',
    logoInitial: 'L'
  },
  {
    id: 'enrich-6',
    name: 'Hunter.io',
    website: 'hunter.io',
    employees: '50+',
    revenue: '$10M',
    coreOffering: 'Email Finder',
    marketShare: 5,
    category: 'Lead Enrichment',
    description: 'Leading solution to find and verify professional email addresses.',
    logoInitial: 'H'
  },
  {
    id: 'enrich-7',
    name: 'RocketReach',
    website: 'rocketreach.co',
    employees: '100+',
    revenue: '$30M',
    coreOffering: 'Contact Search',
    marketShare: 5,
    category: 'Lead Enrichment',
    description: 'Real-time contact search for sales, recruiting, and marketing professionals.',
    logoInitial: 'R'
  },

  // --- Sales Enablement ---
  {
    id: 'sales-1',
    name: 'Seismic',
    website: 'seismic.com',
    employees: '1,500+',
    revenue: '$300M',
    coreOffering: 'Content Management',
    marketShare: 20,
    category: 'Sales Enablement',
    description: '#1 global sales enablement platform for managing content and compliance.',
    logoInitial: 'S'
  },
  {
    id: 'sales-2',
    name: 'Gong',
    website: 'gong.io',
    employees: '1,200+',
    revenue: '$180M',
    coreOffering: 'Revenue Intelligence',
    marketShare: 18,
    category: 'Sales Enablement',
    description: 'Analyzes sales conversations to reveal what top insurance producers do differently.',
    logoInitial: 'G'
  },
  {
    id: 'sales-3',
    name: 'Highspot',
    website: 'highspot.com',
    employees: '1,000+',
    revenue: '$150M',
    coreOffering: 'Guidance & Training',
    marketShare: 12,
    category: 'Sales Enablement',
    description: 'Combines content management with training to ramp up new agents faster.',
    logoInitial: 'H'
  },
  {
    id: 'sales-4',
    name: 'SalesLoft',
    website: 'salesloft.com',
    employees: '800+',
    revenue: '$100M+',
    coreOffering: 'Sales Engagement',
    marketShare: 10,
    category: 'Sales Enablement',
    description: 'Leading platform for creating revenue pipelines and managing deal cycles.',
    logoInitial: 'S'
  },
  {
    id: 'sales-5',
    name: 'Outreach',
    website: 'outreach.io',
    employees: '1,000+',
    revenue: '$150M',
    coreOffering: 'Sales Execution',
    marketShare: 10,
    category: 'Sales Enablement',
    description: 'Helps sales teams efficiently create pipeline and close deals with automation.',
    logoInitial: 'O'
  },
  {
    id: 'sales-6',
    name: 'Allego',
    website: 'allego.com',
    employees: '200+',
    revenue: '$50M',
    coreOffering: 'Learning & Readiness',
    marketShare: 5,
    category: 'Sales Enablement',
    description: 'Sales enablement platform focusing on learning, coaching, and content.',
    logoInitial: 'A'
  },
  {
    id: 'sales-7',
    name: 'Showpad',
    website: 'showpad.com',
    employees: '1,000+',
    revenue: '$100M',
    coreOffering: 'Sales Enablement',
    marketShare: 8,
    category: 'Sales Enablement',
    description: 'Aligns sales and marketing teams to deliver better buyer experiences.',
    logoInitial: 'S'
  },
  {
    id: 'sales-8',
    name: 'Brainshark',
    website: 'brainshark.com',
    employees: '200+',
    revenue: '$50M',
    coreOffering: 'Readiness & Training',
    marketShare: 4,
    category: 'Sales Enablement',
    description: 'Data-driven training and coaching platform for sales readiness.',
    logoInitial: 'B'
  }
];